name: test
on: push

jobs:
  mon-job:
    runs-on: ubuntu-latest
    steps:
      - name: Etape 1
        run: echo "Test OK"

      - name: Etape 2
        if: github.ref == 'refs/heads/master'
        run: echo "Déploiement en cours..."